development:
  cloud_name: klawton1
  api_key: '666448615956826'
  api_secret: cMEOHsPhdjcUVuYXEP0ocAiUphA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: klawton1
  api_key: '666448615956826'
  api_secret: cMEOHsPhdjcUVuYXEP0ocAiUphA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: klawton1
  api_key: '666448615956826'
  api_secret: cMEOHsPhdjcUVuYXEP0ocAiUphA
  enhance_image_tag: true
  static_image_support: false
